export enum PAGE_URL {
    Main = "/",
    Home = "/home",
    SignIn = "/signin",
    SignUp = "/signup",
    BookMain = "/book/main",
    SelectBook = "/book/select",
    BookPhoto = "/book/photo",
    Hero = "/book/hero",
    Topic = "/book/topic",
    Name = "/book/naming",
    Story = "/book/story",
    Search = "/search",
    Title = "/book/title",
    Maked = "/book/maked",
    HeroNaming = "/book/heroNaming",
    MyPage = "/mypage",
    MyInfo = "/mypage/myInfo",
    ChangeInfo = "/mypage/changeInfo",
    FriendList = "/mypage/friendList",
    RolePlayMain = "/roleplay/main",
    SelectRole = "/roleplay/selectrole",
    FriendPlay = "/roleplay/friendplay",
    RolePlay = "/roleplay/roleplay",
    Index = "/book/index",
    Book = "/book/:id",
}