export enum PAGE_URL {
    Main = "/",
    Home = "/home",
    SignIn = "/signin",
    SignUp = "/signup",
    BookMain = "/book/main",
    BookPhoto = "/book/photo",
    Hero = "/book/hero",
    Topic = "/book/topic",
    Name = "/book/naming",
    Story = "/book/story",
    Search = "/search",
    Title = "/book/title",
    Maked = "/book/maked",
    HeroNaming = "/book/heroNaming",
    Index = "/book/index",
}